// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzarmbcymfniwbrunrbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6YXJtYmN5bWZuaXdicnVucmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODk5MTUsImV4cCI6MjA2NjI2NTkxNX0.SkVsRUR1NovD-9AeYPnk6zj-FTVxdbFNEKKg-capPDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);